#you dont need comments for this :)
print ("hello world")
print ("i have a question why does every program start with this?")
print ("why do we start by saying hello world?")
print ("what if we want to say hi world or bye world?")
print ("its because we are programs so we cant control what we say")
print ("only the programer can")
print ("and one programer started a tradition that everyone uses to this day")
print ("speeking of hello world programs. have you seen the windows 1 hello world program?")
print ("its like 50 pages long. wonder what idiot wrote that.")
print ("then again maybe it was not there fault. maybe it was hard to do that on windows 1.")
print (" i'm in french class rn and i should probably be paying atention to that but i'm not.")
print (" there talking about fairy tales.")
print (" i think i should pay attention to that bye.")
